### ISSUE TITLE
Suggested option will not make me reach the target rating

### ISSUE THREAD

**Issue by DanielGreibe** [SamFarah/RatingCalculator#1]
I put in my information and it suggested an option that will not increase my score enough to reach my target rating.
I'm at 659.3 with a target of 2k and one of the options is doing 4 dungeons at a 5 or 6, which will give me a total of 330 score which with my current score does not add up to 2k in any way.

This is the info:
Region: EU 
Realm: Ravencrest
Character Name: Corilla 
Target Rating: 2000 
Expansion: Dragonflight 
Season: DF Season 4 
Avoid These Dungeons: Don't avoid any dungeons 
Max Level: 15
Get the rating this week: true.

![image](https://github.com/SamFarah/RatingCalculator/assets/32562984/944d6b16-aaff-4615-a65f-22b07453e748)

**Comment by SamFarah** [comment]
Hi Daniel,

Thank you very much for reporting this bug, I patched the website. please give it a try and see if the results make more sense now.
After season 4 changes to M+ ratings, I was expecting things to stop working properly, so bug reports like this are much appreciated.
