### ISSUE TITLE
Thanks for figuring this out

### ISSUE THREAD

**Issue by elicwhite** [SamFarah/RatingCalculator#3]
I'm incorporating your values into my weak aura that I use with my friends to figure out which dungeons will collectively increase our rating gain the most. https://wago.io/EkUYyjIUI

Thanks for providing a data source that lets me update this. I'm sure I'll need to update it again in the future as you figure out higher key levels. It would be great to figure out what the pattern is behind the values for higher keys. I'm sure we'll get there over this expansion :) 

(You can close this issue since I'm not reporting a bug. I just wanted to share my appreciation)

**Comment by SamFarah** [comment]
thank you for the kinds words. I'm glad I could help, and thank you for mentioning me on the wago page, I shall import that WA and give it a try.

as for higher (than 12) keys, see if this helps:
So from what I can gather to calculate the base score of a key
the formula is
125 + (5 if the key level >=7)  + (15 * key level) + (10 * number of affixes)

so for example if the key level is 2 (which means it has 1 affix)
then the base score for it is 125 + (15 * 2) + (10 * 1) = 165
and if the key level is 12 (so 4 affixes) then base score = 125 + 5 + (15 * 12)  + (10 * 4)  = 350

so you can use this formula to calculate base score of any level dungoen  and then use the remaining formulas displayed on the main page of mythicplanner.com to get actual score from completion time.

keep in mind I am not 100% sure about this formula, it made sense with data on raider.io at the time (when I figured this out) the highest key on raider.io was an 11 so I couldn't confirm it. I bet now people have much higher keys so I will confirm that formula when I get the chance. once confirmed or adjusted I will update the main page explanation to include this.

I hope this helps.

**Comment by elicwhite** [comment]
Oh awesome. That looks in the realm of possibility based on what the math was last expansion.

For my WA, luckily I don't need min and max scores, just the base.

Do we know if doing the dungeons on any other affix weeks will change the score? Right now I just have it calculating the max score of any affix combo you have for that dungeon.

**Comment by SamFarah** [comment]
Min and max are easy to figure out anyways, 
Max = base score + 15
Min = base score - 30 (well technically min is 0, but you get some score if you were still within 40% over the timer. the moment you miss the timer you instantly lose 15 points from the base, and then for the next 40% of the total time you lose some until it adds up to another 15 (totaling to the - 30 mentioned above) then 1 millisecond beyond that you get 0 points.

As for the weekly affixes and scoring, as far as I know, they have removed the duel score system, no more tyrannical week score and fortified week score. 

This article talks about that a bit https://www.wowhead.com/news/keystone-master-much-easier-in-war-within-new-score-system-basics-346725

the only affixes that rotates weekly are the level 2 one (the Xal'atath's Bargain one) and the fort /tyr you get at level 4 alternating weekly as the used to, but at level 10 or higher you get both of them at the same time anyway. which I guess why they removed the dual scoring system.

**Comment by SamFarah** [comment]
looking at runs on raider.io I noticed that keys LVL 12 or higher seem to get an additional 15 points making the formula 
125 + (5 if the key level >=7)  + (15 if the key level >=12) + (15 * key level) + (10 * number of affixes)

I'm not really convinced that's the actual formula now, seems like there is probably something more robust on calculating it. because who knows maybe there more additional points when the key is higher than her another key level. I will keep an eye but in all cases I updated the table in the main mythic planner website

**Comment by elicwhite** [comment]
For what it's worth, the score calculation from dragonflight was 

```
if rg.keyLevel < 5 then
        rg.newScore = (rg.keyLevel+10)*5 + 30 + (rg.keyLevel)*2
    elseif rg.keyLevel < 10 then
        rg.newScore = (rg.keyLevel+10)*5 + 40 + (rg.keyLevel)*2
    else
        rg.newScore = (rg.keyLevel+10)*5 + 50 + (rg.keyLevel)*2
    end
```

based on the code from this addon: https://www.curseforge.com/wow/addons/mythic-plus-rating-gain

which I had in my previous version of the weakaura: https://wago.io/EkUYyjIUI/1.0.12

so I wouldn't write off what you came up with as needing something "more robust".
